# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marauders' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marauders
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'CryptoSwift'
	pod 'GoogleSignIn'
	pod 'FBSDKLoginKit'
	pod 'FBSDKCoreKit'

  target 'MaraudersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MaraudersUITests' do
    # Pods for testing
  end

end
